name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  Build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v1
        with:
          path: .build
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-
      - name: Install xcpretty
        run: gem install xcpretty
      - name: SwiftFormat # this is necessary since we'll format files in build phase
        run: swift run -c release swiftformat ../ --lint
        working-directory: ./BuildTools
      - name: Switch Xcode version
        run: sudo xcode-select -s /Applications/Xcode_12.4.app
      - name: Build
        run: xcodebuild -scheme eul -project ./eul.xcodeproj -sdk macosx build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED="NO" CODE_SIGN_ENTITLEMENTS="" CODE_SIGNING_ALLOWED="NO" | xcpretty && exit ${PIPESTATUS[0]}
